---

name:
    shopify-to-avatax
version:
    0.1.0.0
# synopsis:
# description:
homepage:
    https://github.com/prikhi/shopify-to-avatax#readme
license:
    BSD3
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2020 Pavan Rikhi
category:
    Web
extra-source-files:
    - README.md

dependencies:
    - base >= 4.7 && < 5

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -with-rtsopts "-N -T"
    - -O2
    - -threaded

library:
    source-dirs:
        src
    dependencies:
        - bytestring
        - cassava
        - ilist
        - scientific
        - text
        - vector

executable:
    main:
        Main.hs
    source-dirs:
        app
    dependencies:
        - shopify-to-avatax
        - bytestring
        - cassava
